var ab=document.getElementById("main");
var a=document.createElement("div");
var b=document.createTextNode("login page");
var c=document.createElement("input");
var d=document.createElement("button");
var e=document.createTextNode("Click");
d.appendChild(e);
a.appendChild(b);
a.appendChild(c);
a.appendChild(d);
document.body.appendChild(a,ab);